### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by guitmz** [jaffee/commandeer#1]
Hi, very nice package :) 

Just pointing out a small typo in your readme, I believe the following part:
```
$ ./myapp
5 gophers stole my jeep!
$ ./myapp
3 gophers stole my horse!
```

Should be:

```
$ ./myapp
5 gophers stole my jeep!
$ ./myapp -num 3
3 gophers stole my horse!
```

With the `-num 3` flag included. Am I correct?

**Comment by jaffee** [comment]
good eye! Thanks for letting me know :)
